version: '3.9'

services:
  service-discovery:
    container_name: ${SERVICE_DISCOVERY_HOST}
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        SERVICE_DISCOVERY_PORT_INNER: ${SERVICE_DISCOVERY_PORT_INNER}
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${SERVICE_DISCOVERY_PORT_OUTER}:${SERVICE_DISCOVERY_PORT_INNER}