spring:
  application:
    name: ${AUTHENTICATION_SERVICE_HOST}

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${AUTHENTICATION_SERVICE_PORT}
