spring:
  application:
    name: ${AUTHENTICATION_SERVICE_HOST}

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

grpc:
  client:
    user-database-grpc-service:
      address: discovery:///${USER_DATABASE_MANAGER_SERVICE}
      negotiation-type: plaintext

server:
  port: ${AUTHENTICATION_SERVICE_PORT}
